import { isAutoMergeEligibleStage, shouldAutoMergeEvidence } from "./evidence";

const GITHUB_API = "https://api.github.com";
const RESEARCH_REPOSITORY = "evaluchat/research";

type GithubJson = Record<string, any>;

function githubHeaders(): HeadersInit {
  const token = process.env.VALERY_GITHUB_TOKEN;
  if (!token) throw new Error("VALERY_GITHUB_TOKEN is not configured");
  return {
    Accept: "application/vnd.github+json",
    Authorization: `Bearer ${token}`,
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "canvas-evidence-runtime",
  };
}

async function githubRequest(
  path: string,
  init: RequestInit = {}
): Promise<GithubJson> {
  const response = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: { ...githubHeaders(), ...(init.headers || {}) },
  });
  const text = await response.text();
  let body: GithubJson = {};
  if (text) {
    try {
      body = JSON.parse(text) as GithubJson;
    } catch {
      body = { message: text };
    }
  }
  if (!response.ok) {
    throw new Error(
      `GitHub API ${response.status}: ${String(body.message || "request failed")}`
    );
  }
  return body;
}

function safeBranchPart(value: string): string {
  return value.replace(/[^a-zA-Z0-9._-]/g, "-");
}

function jsonBody(value: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(value),
  };
}

async function sleep(milliseconds: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, milliseconds));
}

async function waitForOkfLint(
  sha: string
): Promise<{ passed: boolean; conclusion?: string }> {
  const attempts = Math.max(
    1,
    Number.parseInt(process.env.EVIDENCE_GITHUB_CHECK_ATTEMPTS || "10", 10) ||
      10
  );
  const intervalMs = Math.max(
    0,
    Number.parseInt(
      process.env.EVIDENCE_GITHUB_CHECK_INTERVAL_MS || "1000",
      10
    ) || 1000
  );
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    const body = await githubRequest(
      `/repos/${RESEARCH_REPOSITORY}/commits/${encodeURIComponent(sha)}/check-runs?per_page=100`,
      { method: "GET" }
    );
    const checkRuns = Array.isArray(body.check_runs) ? body.check_runs : [];
    const check = checkRuns.find(
      (candidate: GithubJson) => candidate.name === "okf-lint"
    );
    if (check?.conclusion === "success") {
      return { passed: true, conclusion: "success" };
    }
    if (
      check?.conclusion &&
      ["failure", "cancelled", "timed_out", "action_required"].includes(
        check.conclusion
      )
    ) {
      return { passed: false, conclusion: check.conclusion };
    }
    if (attempt + 1 < attempts && intervalMs > 0) await sleep(intervalMs);
  }
  return { passed: false };
}

export type OpenEvidencePullRequestInput = {
  methodId: string;
  methodTitle?: string;
  stage: string;
  timestampSlug: string;
  filePath: string;
  markdown: string;
};

export type OpenEvidencePullRequestResult = {
  number: number;
  url: string;
  branch: string;
  status: "submitted" | "filed";
  lintConclusion?: string;
};

/** Open and, when policy permits, merge the bot-authored research PR. */
export async function openEvidencePullRequest(
  input: OpenEvidencePullRequestInput
): Promise<OpenEvidencePullRequestResult> {
  const baseRef = await githubRequest(
    `/repos/${RESEARCH_REPOSITORY}/git/ref/heads/main`,
    { method: "GET" }
  );
  const baseSha = baseRef.object?.sha;
  if (typeof baseSha !== "string" || !baseSha) {
    throw new Error("Research main branch did not return a commit SHA");
  }

  const branch = `evidence/${safeBranchPart(input.methodId)}/${safeBranchPart(input.timestampSlug)}`;
  await githubRequest(
    `/repos/${RESEARCH_REPOSITORY}/git/refs`,
    jsonBody({ ref: `refs/heads/${branch}`, sha: baseSha })
  );
  await githubRequest(
    `/repos/${RESEARCH_REPOSITORY}/contents/${input.filePath}`,
    {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `docs(evidence): ${input.methodId} evidence ${input.timestampSlug}`,
        content: Buffer.from(input.markdown, "utf8").toString("base64"),
        branch,
      }),
    }
  );

  const pullRequest = await githubRequest(
    `/repos/${RESEARCH_REPOSITORY}/pulls`,
    jsonBody({
      title: `docs(evidence): ${input.methodId} evidence ${input.timestampSlug}`,
      head: branch,
      base: "main",
      body: [
        "This bot-authored evidence contribution was assembled from one concluded method run.",
        "",
        `- Method: ${input.methodId}`,
        `- Stage: ${input.stage}`,
        "- Student identifiers, raw student material, and transcripts are excluded.",
        "- Generated by: canvas-evidence-runtime/0.1",
      ].join("\n"),
    })
  );
  const number = pullRequest.number;
  const url = pullRequest.html_url;
  const headSha = pullRequest.head?.sha;
  if (typeof number !== "number" || typeof url !== "string") {
    throw new Error("GitHub pull request response was incomplete");
  }

  if (!isAutoMergeEligibleStage(input.stage)) {
    await githubRequest(
      `/repos/${RESEARCH_REPOSITORY}/issues/${number}/comments`,
      jsonBody({
        body: "This evidence contribution is routed to human review per the evidence-publishing design because its declared stage is above `documented-experience`.",
      })
    );
    return { number, url, branch, status: "submitted" };
  }

  const lint =
    typeof headSha === "string"
      ? await waitForOkfLint(headSha)
      : { passed: false, conclusion: undefined };
  if (
    shouldAutoMergeEvidence({
      stage: input.stage,
      provenancePresent: true,
      consentPresent: true,
      okfLintPassed: lint.passed,
    })
  ) {
    const merge = await githubRequest(
      `/repos/${RESEARCH_REPOSITORY}/pulls/${number}/merge`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          merge_method: "squash",
          commit_title: `docs(evidence): ${input.methodId} evidence ${input.timestampSlug}`,
        }),
      }
    );
    if (merge.merged === true) {
      return {
        number,
        url,
        branch,
        status: "filed",
        lintConclusion: lint.conclusion,
      };
    }
  }

  return {
    number,
    url,
    branch,
    status: "submitted",
    lintConclusion: lint.conclusion,
  };
}
